\clnk{人}&\clnk{人}&\clnk{亻}&human, person, people&\lnk{ren2}{ren2}&\clnk{今}\clnk{仁}\clnk{休}\clnk{位}\clnk{他}&Note similarity to \clnk{八}, which means {\em eight}.&单人旁（亻），人字头（人）\nl
\clnk{口}&\clnk{口}&&mouth, opening&\lnk{kou3}{kou3}&\clnk{古}\clnk{可}\clnk{名}\clnk{告}\clnk{吃}&Note similarity to \clnk{囗}, which always encloses characters, and means {\em enclosure}.&口字旁\nl
\clnk{土}&\clnk{土}&&earth&\lnk{tu3}{tu3}&\clnk{在}\clnk{地}\clnk{型}\clnk{城}\clnk{地}&Note similarity to \clnk{士}, which has a longer upper stroke and shorter bottom one, and means {\em scholar}.&提土旁\nl
\clnk{女}&\clnk{女}&&woman, female&\lnk{nv3}{nv3}&\clnk{好}\clnk{妄}\clnk{始}\clnk{姓}\clnk{她}&&女子旁\nl
\clnk{心}&\clnk{心}&\clnk{忄}，\clnk{⺗}&heart&\lnk{xin1}{xin1}&\clnk{必}\clnk{忙}\clnk{忘}\clnk{性}\clnk{想}&&竖心旁（忄），心字底（心），竖心底（⺗）\nl
\clnk{手}&\clnk{手}&\clnk{扌}，\clnk{龵}&hand&\lnk{shou3}{shou3}&\clnk{持}\clnk{掌}\clnk{打}\clnk{抱}\clnk{押}&&提手旁（扌），看字头（龵），手字旁（手）\nl
\clnk{日}&\clnk{日}&&sun, day&\lnk{ri4}{ri4}&\clnk{早}\clnk{是}\clnk{明}\clnk{时}\clnk{晩}&Note similarity to \clnk{曰}, which is broader and lower, and means {\em to say}. Also note \clnk{白} which means {\em white}.&日字旁\nl
\clnk{月}&\clnk{月}&&moon, month&\lnk{yue4}{yue4}&\clnk{有}\clnk{服}\clnk{青}\clnk{朝}\clnk{能}&This radical is actually two: {\em moon} \clnk{月} and {\em meat} \clnk{肉}, but in modern Chinese, they look the same in most cases.&月字旁\nl
\clnk{木}&\clnk{木}&&tree&\lnk{mu4}{mu4}&\clnk{板}\clnk{根}\clnk{本}\clnk{林}\clnk{来}&Note similarity to \clnk{禾}, which means {\em grain}.&木字旁\nl
\clnk{氵}&\clnk{氵}&\clnk{水}，\clnk{氺}&water&\lnk{shui3}{shui3}&\clnk{永}\clnk{泳}\clnk{海}\clnk{洋}\clnk{沙}&Note similarity to \clnk{冫}, which means {\em ice}.&水字旁（水），三点水（氵），泰字底水（氺）\nl
\clnk{火}&\clnk{火}&\clnk{灬}&fire&\lnk{huo3}{huo3}&\clnk{灯}\clnk{炎}\clnk{点}\clnk{然}\clnk{炸}&&火字旁（火），四点底（灬）\nl
\clnk{纟}&\clnk{糹}&\clnk{糸}&silk&\lnk{mi4}{(mi4)}&\clnk{纪}\clnk{纸}\clnk{累}\clnk{细}\clnk{绩}&&绞丝旁（纟），独立绞丝（糸）\nl
\clnk{艹}&\clnk{艹}&\clnk{艸}&grass&\lnk{cao3}{cao3}&\clnk{花}\clnk{英}\clnk{苦}\clnk{草}\clnk{茶}&Note that when the radical is on top, the traditional variant has four strokes.&草字头（艹）\nl
\clnk{讠}&\clnk{訁}&\clnk{言}&speech&\lnk{yan2}{yan2}&\clnk{说}\clnk{讲}\clnk{识}\clnk{评}\clnk{试}&&言字旁（讠）\nl
\clnk{辶}&\clnk{辶}&\clnk{辵}&walk&\lnk{chuo4}{(chuo4)}&\clnk{迎}\clnk{通}\clnk{道}\clnk{这}\clnk{近}&&走之旁（辶）\nl
\clnk{钅}&\clnk{釒}&\clnk{金}&gold, metal&\lnk{jin1}{jin1}&\clnk{银}\clnk{针}\clnk{钱}\clnk{铁}\clnk{钟}&&金字旁（钅）\nl
\clnk{刂}&\clnk{刂}&\clnk{刀}&knife, sword&\lnk{dao1}{dao1}&\clnk{分}\clnk{切}\clnk{别}\clnk{利}\clnk{刻}&Note similarity to \clnk{力}, which means {\em force}.&立刀旁（刂），刀字旁（刀）\nl
\clnk{宀}&\clnk{宀}&&roof&\lnk{mian2}{(mian2)}&\clnk{守}\clnk{家}\clnk{室}\clnk{字}\clnk{宅}&Note similarity to \clnk{冖}, which means {\em cover}, and to \clnk{亠}, which means {\em lid}.&宝盖头\nl
\clnk{贝}&\clnk{貝}&&shell&\lnk{bei4}{bei4}&\clnk{财}\clnk{贪}\clnk{货}\clnk{贸}\clnk{负}&Note similarity to \clnk{见}, which means {\em to see}.&贝字旁\nl
\clnk{一}&\clnk{一}&&one&\lnk{yi1}{yi1}&\clnk{三}\clnk{上}\clnk{下}\clnk{不}\clnk{两}&&横\nl
\clnk{力}&\clnk{力}&&power, force&\lnk{li4}{li4}&\clnk{力}\clnk{加}\clnk{助}\clnk{勉}\clnk{动}&Note similarity to \clnk{刀}, which means {\em knife}.&力字旁\nl
\clnk{又}&\clnk{又}&&right hand&\lnk{you4}{you4}&\clnk{反}\clnk{取}\clnk{受}\clnk{友}\clnk{发}&&又字旁\nl
\clnk{犭}&\clnk{犭}&\clnk{犬}&dog&\lnk{quan3}{(quan3)}&\clnk{犯}\clnk{狂}\clnk{狗}\clnk{献}\clnk{猪}&Note similarity to \clnk{大}, which means {\em big}.&反犬旁（犭），犬字旁（犬）\nl
\clnk{禾}&\clnk{禾}&&grain&\lnk{he2}{(he2)}&\clnk{私}\clnk{科}\clnk{秒}\clnk{秀}\clnk{秘}&Note similarity to \clnk{木}, which means {\em tree}.&禾木旁\nl
\clnk{⺮}&\clnk{⺮}&\clnk{竹}&bamboo&\lnk{zhu2}{zhu2}&\clnk{笑}\clnk{第}\clnk{简}\clnk{筷}\clnk{算}&&竹子头（竹字头）\nl
\clnk{虫}&\clnk{虫}&&insect&\lnk{chong2}{chong2}&\clnk{強}\clnk{独}\clnk{蛇}\clnk{蛋}\clnk{蚊}&Even though this radical means {\em insect}, it's used for many organisms which aren't insects according to our taxonomy.&虫字旁\nl
\clnk{阝}:&\clnk{阝}:&\clnk{阜}&mound, dam&\lnk{fu4}{(fu4)}&\clnk{防}\clnk{阻}\clnk{陆}\clnk{院}\clnk{陈}&Note that there are two radicals which look like this. On the left, it means {\em mound, dam}, and on the right, it means {\em city}.&双耳刀（左耳刀）\nl
\clnk{大}&\clnk{大}&&big, very&\lnk{da4}{da4}&\clnk{天}\clnk{尖}\clnk{因}\clnk{奇}\clnk{美}&&大字旁（头）\nl
\clnk{广}&\clnk{广}&&house on cliff&\lnk{guang3}{guang3}&\clnk{店}\clnk{府}\clnk{度}\clnk{座}\clnk{庭}&Note similarity to \clnk{厂}, which means {\em cliff} (i.e. without the house).&广字旁\nl
\clnk{田}&\clnk{田}&&field&\lnk{tian2}{tian2}&\clnk{思}\clnk{留}\clnk{略}\clnk{番}\clnk{累}&&田字旁\nl
\clnk{目}&\clnk{目}&\clnk{罒}&eye&\lnk{mu4}{mu4}&\clnk{眼}\clnk{睛}\clnk{看}\clnk{相}\clnk{省}&Note that the horizontal version can also mean {\em net}.&目字旁（目），四字头（罒）\nl
\clnk{石}&\clnk{石}&&stone&\lnk{shi2}{shi2}&\clnk{砂}\clnk{破}\clnk{碑}\clnk{矿}\clnk{码}&&石字旁\nl
\clnk{衤}&\clnk{衤}&\clnk{衣}&clothes&\lnk{yi1}{yi1}&\clnk{初}\clnk{被}\clnk{裁}\clnk{裤}\clnk{袜}&Note similarity to \clnk{礻}, which means {\em sign, show} or {\em spirit}.&衣字旁（衤）\nl
\clnk{足}&\clnk{足}&\clnk{⻊}&foot&\lnk{zu2}{zu2}&\clnk{跑}\clnk{跨}\clnk{跟}\clnk{路}\clnk{距}&&足字旁\nl
\clnk{马}&\clnk{馬}&&horse&\lnk{ma3}{ma3}&\clnk{码}\clnk{驾}\clnk{骂}\clnk{驻}\clnk{妈}&&马字旁\nl
\clnk{页}&\clnk{頁}&&leaf&\lnk{ye4}{ye4}&\clnk{顺}\clnk{须}\clnk{领}\clnk{预}\clnk{顶}&&页字旁\nl
\clnk{巾}&\clnk{巾}&&turban, scarf&\lnk{jin1}{(jin1)}&\clnk{市}\clnk{布}\clnk{帝}\clnk{帐}\clnk{帽}&&巾字旁\nl
\clnk{米}&\clnk{米}&&rice&\lnk{mi3}{mi3}&\clnk{类}\clnk{粉}\clnk{迷}\clnk{粗}\clnk{糖}&&米字旁\nl
\clnk{车}&\clnk{車}&&cart, vehicle&\lnk{che1}{che1}&\clnk{轮}\clnk{软}\clnk{军}\clnk{较}\clnk{输}&&车字旁\nl
\clnk{八}&\clnk{八}&&eight&\lnk{ba1}{ba1}&\clnk{公}\clnk{分}\clnk{趴}\clnk{兵}\clnk{共}&Note similarity to \clnk{人}, which means {\em human, person}.&八字旁（头）\nl
\clnk{尸}&\clnk{尸}&&corpse&\lnk{shi1}{shi1}&\clnk{尺}\clnk{局}\clnk{尾}\clnk{居}\clnk{展}&Note similarity to \clnk{戶}, which means {\em door, family}.&尸字头\nl
\clnk{寸}&\clnk{寸}&&thumb, inch&\lnk{cun4}{cun4}&\clnk{寺}\clnk{尊}\clnk{对}\clnk{射}\clnk{付}&&寸字旁\nl
\clnk{山}&\clnk{山}&&mountain&\lnk{shan1}{shan1}&\clnk{岩}\clnk{岛}\clnk{岁}\clnk{崗}\clnk{岔}&&山字旁（头）\nl
\clnk{攵}&\clnk{攵}&\clnk{攴}&knock, tap&\lnk{pu1}{(pu1)}&\clnk{收}\clnk{改}\clnk{攻}\clnk{做}\clnk{政}&Note similarity to \clnk{夊}, which means {\em to walk (slowly)}.&反文旁（攵），旧反文旁（攴）\nl
\clnk{彳}&\clnk{彳}&&(small) step&\lnk{chi2}{(chi2)}&\clnk{彼}\clnk{很}\clnk{律}\clnk{微}\clnk{德}&Note similarity to \clnk{亻}, which means {\em human, person}.&双人旁\nl
\clnk{十}&\clnk{十}&&ten&\lnk{shi2}{shi2}&\clnk{什}\clnk{计}\clnk{古}\clnk{叶}\clnk{早}&&十字旁（头）\nl
\clnk{工}&\clnk{工}&&work&\lnk{gong1}{gong1}&\clnk{左}\clnk{江}\clnk{红}\clnk{巧}\clnk{功}&&工字旁\nl
\clnk{方}&\clnk{方}&&square, raft&\lnk{fang1}{fang1}&\clnk{放}\clnk{旅}\clnk{族}\clnk{仿}\clnk{房}&Note similarity to \clnk{万}, which means {\em ten thousand}.&方字旁\nl
\clnk{门}&\clnk{門}&&gate&\lnk{men2}{men2}&\clnk{间}\clnk{闲}\clnk{问}\clnk{闭}\clnk{闻}&&门字框\nl
\clnk{饣}&\clnk{飠}&\clnk{食}&eat, food&\lnk{shi2}{shi2}&\clnk{饭}\clnk{饿}\clnk{饮}\clnk{馆}\clnk{饱}&&食字旁\nl
\clnk{欠}&\clnk{欠}&&lack, yawn&\lnk{qian4}{qian4}&\clnk{欢}\clnk{欧}\clnk{欲}\clnk{次}\clnk{歌}&&欠字旁\nl
\clnk{儿}&\clnk{儿}&&human, legs&\lnk{er2}{er2}&\clnk{元}\clnk{四}\clnk{光}\clnk{兄}\clnk{充}&Note similarity to \clnk{人}, which means {\em human, person}, and to \clnk{八} which means {\em eight}.&儿座底\nl
\clnk{冫}&\clnk{冫}&&ice&\lnk{bing1}{bing1}&\clnk{冬}\clnk{冷}\clnk{冻}\clnk{况}\clnk{净}&&两点水\nl
\clnk{子}&\clnk{子}&&child, seed&\lnk{zi3}{zi3}&\clnk{字}\clnk{学}\clnk{存}\clnk{孩}\clnk{季}&&子字旁\nl
\clnk{疒}&\clnk{疒}&&sickness&\lnk{ne4}{(ne4)}&\clnk{病}\clnk{痛}\clnk{疗}\clnk{疯}\clnk{痩}&&病字旁\nl
\clnk{隹}&\clnk{隹}&&(short-tailed) bird&\lnk{zhui1}{(zhui1)}&\clnk{雀}\clnk{集}\clnk{难}\clnk{雅}\clnk{谁}&&隹字旁\nl
\clnk{斤}&\clnk{斤}&&axe, pound&\lnk{jin1}{(jin1)}&\clnk{所}\clnk{新}\clnk{听}\clnk{近}\clnk{析}&&斤字旁\nl
\clnk{亠}&\clnk{亠}&&lid&\lnk{tou2}{(tou2)}&\clnk{亡}\clnk{交}\clnk{京}\clnk{产}\clnk{亮}&Note similarity to \clnk{宀}, which means {\em roof,} and \clnk{冖} which means {\em cover}.&点横头\nl
\clnk{王}&\clnk{王}&\clnk{玉}&jade, king&\lnk{yu4, wang2}{yu4, wang2}&\clnk{主}\clnk{弄}\clnk{皇}\clnk{理}\clnk{现}&This radical is \clnk{玉}, but when in composition, it looks like \clnk{王}, {\em king}, and is probably more easily remembered like that.&王字旁\nl
\clnk{白}&\clnk{白}&&white&\lnk{bai2}{bai2}&\clnk{的}\clnk{皆}\clnk{皇}\clnk{怕}\clnk{迫}&Note similarity to \clnk{日}, which means {\em sun}.&白字旁\nl
\clnk{立}&\clnk{立}&&stand, erect&\lnk{li4}{li4}&\clnk{音}\clnk{意}\clnk{端}\clnk{亲}\clnk{位}&&立字旁\nl
\clnk{羊}&\clnk{羊}&\clnk{⺶}，\clnk{⺷}&sheep&\lnk{yang2}{yang2}&\clnk{着}\clnk{样}\clnk{洋}\clnk{美}\clnk{鲜}&&羊字旁\nl
\clnk{艮}&\clnk{艮}&&stopping&\lnk{gen4}{(gen4)}&\clnk{很}\clnk{恨}\clnk{恳}\clnk{根}\clnk{眼}&&艮字旁\nl
\clnk{冖}&\clnk{冖}&&cover&\lnk{mi4}{(mi4)}&\clnk{写}\clnk{军}\clnk{农}\clnk{深}\clnk{荣}&&秃宝盖\nl
\clnk{厂}&\clnk{厂}&&cliff&\lnk{han4}{(han4)}&\clnk{厚}\clnk{原}\clnk{厉}\clnk{厅}\clnk{厕}&Note similarity to \clnk{广}, which has a house on top (the dot).&厂字旁\nl
\clnk{皿}&\clnk{皿}&&dish&\lnk{min3}{(min3)}&\clnk{盆}\clnk{监}\clnk{盟}\clnk{盛}\clnk{盖}&&皿字底\nl
\clnk{礻}&\clnk{礻}&\clnk{示}&sign, spirit, show&\lnk{shi4}{shi4}&\clnk{社}\clnk{神}\clnk{视}\clnk{祝}\clnk{祥}&Note similarity to \clnk{衤}, which means {\em clothes}.&示字旁\nl
\clnk{穴}&\clnk{穴}&&cave&\lnk{xue4}{xue4}&\clnk{空}\clnk{突}\clnk{穷}\clnk{究}\clnk{窗}&&穴宝盖\nl
\clnk{走}&\clnk{走}&&run, walk&\lnk{zou3}{zou3}&\clnk{起}\clnk{超}\clnk{越}\clnk{赶}\clnk{徒}&&走字旁\nl
\clnk{雨}&\clnk{雨}&&rain&\lnk{yu3}{yu3}&\clnk{雷}\clnk{雪}\clnk{霜}\clnk{需}\clnk{露}&&雨字头\nl
\clnk{囗}&\clnk{囗}&&enclosure&\lnk{wei2}{(wei2)}&\clnk{回}\clnk{国}\clnk{因}\clnk{图}\clnk{团}&Note similarity to \clnk{口}, which does not enclose other components and means {\em mouth}.&国字框\nl
\clnk{小}&\clnk{小}&\clnk{⺌}&small&\lnk{xiao3}{xiao3}&\clnk{少}\clnk{肖}\clnk{尚}\clnk{尖}\clnk{尘}&&小字旁（头）\nl
\clnk{戈}&\clnk{戈}&&halberd, spear&\lnk{ge1}{(ge1)}&\clnk{成}\clnk{式}\clnk{战}\clnk{感}\clnk{我}&Note similarity to \clnk{弋}, which means {\em catch, arrest}.&戈字旁\nl
\clnk{几}&\clnk{几}&&table&\lnk{ji1}{ji1}&\clnk{朵}\clnk{机}\clnk{风}\clnk{凡}\clnk{凤}&&几字旁\nl
\clnk{舌}&\clnk{舌}&&tongue&\lnk{she2}{she2}&\clnk{乱}\clnk{适}\clnk{话}\clnk{舍}\clnk{活}&&舌字旁\nl
\clnk{干}&\clnk{干}&&dry&\lnk{gan1}{gan1}&\clnk{平}\clnk{刊}\clnk{汗}\clnk{旱}\clnk{赶}&&干字旁\nl
\clnk{殳}&\clnk{殳}&&weapon&\lnk{shu1}{(shu1)}&\clnk{段}\clnk{没}\clnk{投}\clnk{般}\clnk{设}&&殳字旁\nl
\clnk{夕}&\clnk{夕}&&evening, sunset&\lnk{xi1}{xi1}&\clnk{外}\clnk{多}\clnk{夜}\clnk{名}\clnk{岁}&Note similarity to \clnk{歹}, which means {\em bad, vicious}.&夕字旁\nl
\clnk{止}&\clnk{止}&&stop&\lnk{zhi3}{zhi3}&\clnk{正}\clnk{此}\clnk{步}\clnk{歪}\clnk{址}&&止字旁\nl
\clnk{牜}&\clnk{牜}&\clnk{牛}，\clnk{⺧}&cow&\lnk{niu2}{niu2}&\clnk{告}\clnk{物}\clnk{解}\clnk{特}\clnk{件}&&牛字旁（头）\nl
\clnk{皮}&\clnk{皮}&&skin&\lnk{pi2}{pi2}&\clnk{披}\clnk{彼}\clnk{波}\clnk{破}\clnk{疲}&&皮字旁\nl
\clnk{耳}&\clnk{耳}&&ear&\lnk{er3}{er3}&\clnk{取}\clnk{闻}\clnk{职}\clnk{聪}\clnk{联}&&耳字旁\nl
\clnk{辛}&\clnk{辛}&&bitter&\lnk{xin1}{xin1}&\clnk{辜}\clnk{辟}\clnk{辣}\clnk{辨}\clnk{辩}&&辛字旁\nl
:\clnk{阝}&:\clnk{阝}&\clnk{邑}&city&\lnk{yi4}{(yi4)}&\clnk{那}\clnk{邦}\clnk{部}\clnk{都}\clnk{邮}&Note that there are two radicals which look like this. On the left, it means {\em mound, dam}, and on the right, it means {\em city}.&双耳刀（右耳刀）\nl
\clnk{酉}&\clnk{酉}&&wine&\lnk{you3}{(you3)}&\clnk{醉}\clnk{酒}\clnk{醒}\clnk{酸}\clnk{尊}&&酉字旁\nl
\clnk{青}&\clnk{青}&&green/blue&\lnk{qing1}{qing1}&\clnk{请}\clnk{清}\clnk{情}\clnk{晴}\clnk{猜}&&青字旁\nl
\clnk{鸟}&\clnk{鳥}&&bird&\lnk{niao3}{niao3}&\clnk{鸦}\clnk{鸣}\clnk{鸭}\clnk{岛}\clnk{鸡}&Note similarity to \clnk{乌}, which means {\em crow, black}.&鸟字旁\nl
\clnk{弓}&\clnk{弓}&&bow&\lnk{gong1}{gong1}&\clnk{引}\clnk{张}\clnk{弱}\clnk{第}\clnk{强}&&弓字旁\nl
\clnk{厶}&\clnk{厶}&&private&\lnk{si1}{si1}&\clnk{公}\clnk{勾}\clnk{去}\clnk{私}\clnk{云}&&私字旁\nl
\clnk{户}&\clnk{户}&\clnk{戶}&door, house&\lnk{hu4}{hu4}&\clnk{所}\clnk{房}\clnk{炉}\clnk{护}\clnk{启}&Note similarity to \clnk{尸}, which means {\em corpse}.&户字旁\nl
\clnk{羽}&\clnk{羽}&&feather&\lnk{yu3}{yu3}&\clnk{习}\clnk{翻}\clnk{翅}\clnk{塌}\clnk{扇}&&羽字旁\nl
\clnk{舟}&\clnk{舟}&&boat&\lnk{chuan2}{chuan2}&\clnk{般}\clnk{船}\clnk{航}\clnk{盘}\clnk{艇}&&舟字旁\nl
\clnk{里}&\clnk{里}&&village, mile&\lnk{li3}{li3}&\clnk{野}\clnk{重}\clnk{量}\clnk{理}\clnk{埋}&&里字旁\nl
\clnk{匕}&\clnk{匕}&&spoon&\lnk{bi3}{(bi3)}&\clnk{匙}\clnk{比}\clnk{北}\clnk{呢}\clnk{旨}&&匕字旁\nl
\clnk{夂}&\clnk{夂}&&go (slowly)&\lnk{sui1}{(sui1)}&\clnk{各}\clnk{條}\clnk{复}\clnk{备}\clnk{夏}&Note similarity to \clnk{攵}, which means {\em to knock, to rap}.&折文旁\nl
\clnk{见}&\clnk{見}&&see&\lnk{jian4}{jian4}&\clnk{观}\clnk{规}\clnk{视}\clnk{现}\clnk{觉}&Note similarity to \clnk{贝}, which means {\em shell}.&见字旁\nl
\clnk{卩}&\clnk{卩}&&seal&\lnk{jie2}{(jie2)}&\clnk{卷}\clnk{印}\clnk{却}\clnk{即}\clnk{危}&&单耳刀\nl
\clnk{罒}&\clnk{罒}&\clnk{网}&net&\lnk{wang3}{wang3}&\clnk{罗}\clnk{罚}\clnk{罢}\clnk{罪}\clnk{罩}&Note that the horizontal version can also mean {\em net}.&四字头（罒）\nl
\clnk{士}&\clnk{士}&&scholar&\lnk{shi4}{shi4}&\clnk{吉}\clnk{壶}\clnk{志}\clnk{声}\clnk{壮}&Note similarity to \clnk{土}, which means {\em earth}.&士字旁\nl
\clnk{勹}&\clnk{勹}&&embrace, wrap&\lnk{bao1}{(bao1)}&\clnk{包}\clnk{勿}\clnk{勾}\clnk{勺}\clnk{勻}&&包字头\nl
