name: Build PDF document
on:
  push:
    branches:
      - main
    paths: 
      - '**.tex'
  pull_request:
    branches:
      - main
    paths: 
      - '**.tex'  
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile XeLaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: "font-noto font-noto-cjk font-noto-cjk-extra"
          pre_compile: > 
            pushd /usr/share/fonts; 
            mkdir kaiti; 
            cd kaiti; 
            wget https://github.com/dolbydu/font/raw/master/unicode/STKaiti.TTF; 
            wget https://github.com/dolbydu/font/raw/master/unicode/Kaiti.ttf;
            wget https://github.com/dolbydu/font/raw/master/unicode/Adobe%20Kaiti%20Std.otf; 
            popd
          root_file: 100-most-common-radicals.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - name: Upload PDF to workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: 100 Most Common Radicals PDF
          path: 100-most-common-radicals.pdf
          
